### ISSUE TITLE
Calling an anonymous function causes an error

### ISSUE THREAD

**Issue by xyproto** [dave/jennifer#66]
Hi,

Thanks for creating `jennifer`.

I`m trying to create and call an anonymous function, but it does not seem to work.

Here is an example program:

```go
package main

import (
	"fmt"

	"github.com/dave/jennifer/jen"
)

func main() {
	// This works
	fmt.Println(func(x float64) float64 { return 0.5 * x }(0.5))

	// Building the anonymous function and passing a parameter works
	expression := jen.Func().Params(
		jen.Id("x").Id("float64"),
	).Id("float64").Block(
		jen.Return().Lit(0.5).Op("*").Id("x"),
	).Call(jen.Lit(0.5))

	// This fails
	fmt.Println(expression.GoString())
}
```

Here is the same program on the Go playground: https://play.golang.org/p/In4w6w8wEAs

The error message is:

```
panic: Error 1:36: expected '(', found '{' (and 2 more errors) while formatting source:
func (x float64) float64 {
return  0.5 * x
} (0.5)

goroutine 1 [running]:
github.com/dave/jennifer/jen.(*Statement).GoString(0x40a0f0, 0x43e360, 0x4, 0x4)
	/tmp/gopath017659477/pkg/mod/github.com/dave/jennifer@v1.3.0/jen/statement.go:81 +0x2c0
main.main()
	/tmp/sandbox296010062/prog.go:21 +0xd20
```

**Comment by dave** [comment]
The formatting routine checks for valid go source, so you need to use the anonymous function like a value. This works:

```go
package main

import (
	"fmt"

	"github.com/dave/jennifer/jen"
)

func main() {
	// Building the anonymous function and passing a parameter works
	expression := jen.Id("a").Op(":=").Func().Params(
		jen.Id("x").Id("float64"),
	).Id("float64").Block(
		jen.Return().Lit(0.5).Op("*").Id("x"),
	).Call(jen.Lit(0.5))

	// This fails
	fmt.Println(expression.GoString())
}
```

Output:

```
a := func(x float64) float64 {
	return 0.5 * x
}(0.5)
```

**Comment by xyproto** [comment]
That makes sense. Thanks!
